databaseType = "PostgreSql"
id = "99d6e591-22c1-4572-9b98-1bf924ed431e"
name = "Bluebox Flyway Demo"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineVersion = "001_20240725160738"
baselineOnMigrate = true
publishResult = true
email = "ryan.booz@red-gate.com"

[environments.Production]
schemas = [ "bluebox", "public" ]

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.target3]
url = "jdbc:postgresql://localhost:5434/bluebox1"
schemas = [ "bluebox", "public" ]
displayName = "MineMineMine"
