databaseType = "PostgreSql"
id = "99d6e591-22c1-4572-9b98-1bf924ed431e"
name = "Bluebox Flyway Demo"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true
baselineVersion = "001_20240725160738"
baselineOnMigrate = true
publishResult = false
email = "ryan.booz@red-gate.com"

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.development]
url = "jdbc:postgresql://localhost:5434/bluebox_dev"
schemas = [ "public", "bluebox" ]
displayName = "bluebox_dev"

[environments.build]
url = "jdbc:postgresql://localhost:5434/bluebox_build"
schemas = [ "public", "bluebox" ]
displayName = "bluebox_build"

[environments.staging]
url = "jdbc:postgresql://localhost:5434/bluebox_stage"
schemas = [ "public", "bluebox" ]
displayName = "bluebox_stage"

[environments.production]
url = "jdbc:postgresql://localhost:5434/bluebox_prod"
schemas = [ "public", "bluebox" ]
displayName = "bluebox_prod"
