-- Script generated by Redgate Compare v1.21.3.23109
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.rental_rental_period_upper_null...';END$$;
DROP INDEX bluebox.rental_rental_period_upper_null;

SET check_function_bodies = true;
