-- Script generated by Redgate Compare v1.22.1.23470
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping bluebox.person.place_of_birth2...';END$$;
ALTER TABLE bluebox.person DROP COLUMN place_of_birth2;

SET check_function_bodies = true;
