-- Script generated by Redgate Compare v1.28.0.25641
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.release_type...';END$$;
DELETE FROM bluebox.release_type WHERE release_type_id IN (1, 2, 3, 4, 5, 6);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering bluebox.film_genre...';END$$;
DELETE FROM bluebox.film_genre WHERE genre_id IN (12, 14, 16, 18, 27, 28, 35, 36, 37, 53, 80, 99, 878, 9648, 10402, 10749, 10751, 10752, 10770, 20000, 50000);

SET check_function_bodies = true;
