dialects = ["TEXT"]
rules = ["(?i)(^|\\s+)(create|create\\s+or\\s+replace)\\s+function\\s+(.*)(\\.?)(\\w{35,}).*(?=$|\\s|;)"]
passOnRegexMatch = false
description = "Function name is longer than 35 characters"